### ISSUE TITLE
Status bar is inconsistent when no info is available

### ISSUE THREAD

**Issue by nbrachet** [nbrachet/FlyDrones.iOS#6]
Battery indicator is cross-out, compass is unchanges, map button is grayed out.

All should be grayed out (when no info is available).

**Comment by nab0y4enko** [comment]
Fixed in 0.1.4

**Comment by nbrachet** [comment]
Still not correct!

The battery indicator should NOT be crossed out, simply grayed out.
The compass is not grayed out

**Comment by nab0y4enko** [comment]
Fixed in 0.1.4.3

**Comment by nbrachet** [comment]
Nope: the battery indicator is still crossed out.

**Comment by nab0y4enko** [comment]
I crossed out, if you do not come to any data on the battery. When the indicator is disabled, then the values are not changed.

**Comment by nab0y4enko** [comment]
Also, the battery icon will be crossed if remaining value -1. But in my logs, this was not found
